In [1]:
import pandas as pd
#import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns
import sys
from pathlib import Path
sys.path.append('../../src')
from data_imports import *
import tests
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [17]:
patients = import_patients()
biosamples = import_biosamples(include_hm=True)
#amplicons = import_amplicons()
#genes = import_genes()

In [18]:
def read_consent_withdrawals(file='../../data/source/sjcloud/RTCG_sample_removal_202609_ic.xlsx'):
    return pd.read_excel(file)
withdrawals = read_consent_withdrawals()
withdrawals

   subject_name      sample_name dataset_name
0      SJ030350  SJBALL030350_D1         RTCG
1      SJ030350  SJBALL030350_G1         RTCG
2      SJ030739   SJWLM030739_D1         RTCG
3      SJ030739   SJWLM030739_G1         RTCG
4      SJ030838    SJMB030838_D1         RTCG
5      SJ030838    SJMB030838_G1         RTCG
6      SJ030885   SJAML030885_G1         RTCG
7      SJ030904   SJLGG030904_G1         RTCG
8      SJ030928  SJBALL030928_D1         RTCG
9      SJ030928  SJBALL030928_G1         RTCG
10     SJ031074  SJBALL031074_D1         RTCG
11     SJ031074  SJBALL031074_G1         RTCG
12     SJ031226    SJBT031226_D1         RTCG
13     SJ031226    SJBT031226_G1         RTCG
14     SJ031634  SJTALL031634_D1         RTCG
15     SJ031634  SJTALL031634_G1         RTCG
16     SJ031640  SJTALL031640_D1         RTCG
17     SJ031640  SJTALL031640_G1         RTCG
18     SJ031760   SJAML031760_D1         RTCG
19     SJ031760   SJAML031760_G1         RTCG
20     SJ032154  SJBALL032154_D1         RTCG
21     SJ032154  SJBALL032154_G1         RTCG
22     SJ032266  SJBALL032266_D1         RTCG
23     SJ032266  SJBALL032266_G1         RTCG
24     SJ032608    SJHM032608_G1         RTCG
25     SJ032759   SJAML032759_D1         RTCG
26     SJ032759   SJAML032759_G1         RTCG
27     SJ032759   SJAML032759_R1         RTCG
28     SJ032863   SJNBL032863_D1         RTCG
29     SJ032863   SJNBL032863_D3         RTCG
30     SJ032863   SJNBL032863_G1         RTCG
31     SJ032877   SJRHB032877_D1         RTCG
32     SJ032877   SJRHB032877_G1         RTCG
33     SJ033238    SJMB033238_D1         RTCG
34     SJ033238    SJMB033238_G1         RTCG
35     SJ033394    SJST033394_D1         RTCG
36     SJ033394    SJST033394_G1         RTCG
37     SJ033499    SJST033499_D1         RTCG
38     SJ033499    SJST033499_G1         RTCG
39     SJ033770    SJHM033770_D1         RTCG
40     SJ033888   SJAML033888_D1         RTCG
41     SJ034654   SJEWS034654_G1         RTCG
42     SJ034722    SJRB034722_D1         RTCG
43     SJ034722    SJRB034722_G1         RTCG
44     SJ034733    SJST034733_D1         RTCG
45     SJ034733    SJST034733_D2         RTCG
46     SJ034733    SJST034733_G1         RTCG
47     SJ034798    SJST034798_D1         RTCG
48     SJ034798    SJST034798_G1         RTCG
49     SJ034850    SJBT034850_G1         RTCG
50     SJ034852    SJST034852_G1         RTCG
51     SJ035644    SJST035644_D1         RTCG
52     SJ035644    SJST035644_G1         RTCG
53     SJ035682    SJBT035682_D1         RTCG
54     SJ035682    SJBT035682_G1         RTCG
55     SJ035969    SJHM035969_D1         RTCG
56     SJ035969    SJHM035969_G1         RTCG
57     SJ036056    SJBT036056_D2         RTCG
58     SJ036056    SJBT036056_G1         RTCG
59     SJ036091    SJBT036091_G1         RTCG
60     SJ036129    SJBT036129_G1         RTCG
61     SJ036132    SJHM036132_G1         RTCG
62     SJ036142    SJST036142_D1         RTCG
63     SJ036489  SJDNOS036489_D1         RTCG
64     SJ036489    SJST036489_G1         RTCG
65     SJ036623    SJBT036623_G1         RTCG
66     SJ036689    SJST036689_D1         RTCG
67     SJ036689    SJST036689_G1         RTCG
68     SJ036992    SJST036992_D1         RTCG
69     SJ036992    SJST036992_G1         RTCG
70     SJ037122  SJDNOS037122_G1         RTCG
71     SJ037122    SJST037122_D1         RTCG
72     SJ037140    SJST037140_G1         RTCG
73     SJ037199  SJDNOS037199_G1         RTCG
74     SJ037199    SJST037199_D1         RTCG
75     SJ037554  SJDNOS037554_G1         RTCG

In [19]:
# What patients are withdrawn?
# 3 patients
patients[patients.index.isin(withdrawals.subject_name)]

,sex,race,ethnicity,age_at_diagnosis,cohort,cancer_type,cancer_subclass,amplicon_class,tumor_fraction_THetA2,OS_status,OS_months
patient_id,,,,,,,,,,,
SJ030739,Male,Multiracial,Not Hispanic Or Latino,2674.0,SJC-DS-1007,WT,WT,no amplification,0.326973,Alive,55.786448
SJ032863,Female,Asian,Not Hispanic Or Latino,1530.0,SJC-DS-1007,NBL,NBL,no amplification,0.665570,NaN,NaN
SJ032877,Male,Black Or African American,Not Hispanic Or Latino,5749.0,SJC-DS-1007,RMS,ARMS,no amplification,0.477494,NaN,NaN

In [20]:
# what biosamples are withdrawn?
biosamples[biosamples.index.isin(withdrawals.sample_name)]

,sex,patient_id,external_sample_id,tumor_history,age_at_diagnosis,cohort,extent_of_tumor_resection,tumor_fraction_THetA2,cancer_type,cancer_subclass,ecDNA_sequences_detected,amplicon_class,in_unique_tumor_set,in_unique_patient_set
biosample_id,,,,,,,,,,,,,,
SJWLM030739_D1,Male,SJ030739,NaN,Diagnosis,2674.0,SJC-DS-1007,NaN,0.326973,WT,WT,0,no amplification,True,True
SJNBL032863_D1,Female,SJ032863,NaN,Diagnosis,1530.0,SJC-DS-1007,NaN,0.665570,NBL,NBL,0,no amplification,True,True
SJRHB032877_D1,Male,SJ032877,NaN,Diagnosis,5749.0,SJC-DS-1007,NaN,0.477494,RMS,ARMS,0,no amplification,True,True